### ISSUE TITLE
We need a README

### ISSUE THREAD

**Issue by mmalaquaisdev** [NodeBotsSalvador/nodebotsdayssa-twitter-bot#3]
What do you think write the README using pt-br or english?

**Comment by joanasouza** [comment]
I think that have a README in english would be cool if we want people from different countries to contribute to our project. But we could also use a README in english as a way to practice our communication skills. Maybe, a README in pt-br and also english would be a good way for those who knows english and want to follow things in english and portuguese for the ones who don't understand a single word in english.

**Comment by vinicius73** [comment]
Adding to what @joanasouza said.
We should think about how we feel when we find a project written in Russian.
English is the best way to communicate, keeping readme in pt-BR is not simple and will probably be late, I'd rather not have to keep two.

**Comment by mmalaquaisdev** [comment]
@joanasouza and @vinicius73 thank you guys. In the first time will just maintainthe english README in the future if brazilian people create some interesting for this project i will ask for them help.

I will do because as @vinicius73 sad maintain one doc is very difficult imagine two.
